apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    app: prometheus
    app-tier: monitoring
spec:
  type: NodePort
  ports:
  - port: 9090
  selector:
        app: prometheus
        app-tier: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
    app-tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
        app: prometheus
        app-tier: monitoring
  template:
    metadata:
      labels:
        app: prometheus
        app-tier: monitoring
    spec:
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
      containers:
      - name: prometheus-container
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus
