apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    app-tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
        app: prometheus
        app-tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: networking
  labels:
    app: nginx
    app-tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nginx
        app-tier: frontend
  template:
    metadata:
      labels:
        app: nginx
        app-tier: frontend
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80